services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    container_name: backend
    restart: always
    ports:
      - "8000:8000"

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.build
    volumes:
      - ./frontend_dist/dist:/app/dist
    entrypoint: ["sh", "-c", "npm run build"]

